// Types for userActions.tsx

export const REGISTER_USER_START = 'REGISTER_USER_START';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGOUT_USER_START = 'LOGOUT_USER_START';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';

export const GET_USER_START = 'GET_USER_START';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const ADD_BLOGPOST_START = 'ADD_BLOGPOST_START';
export const ADD_BLOGPOST_SUCCESS = 'ADD_BLOGPOST_SUCCESS';
export const ADD_BLOGPOST_ERROR = 'ADD_BLOGPOST_ERROR';


export const EDIT_BLOGPOST_START = 'EDIT_BLOGPOST_START';
export const EDIT_BLOGPOST_SUCCESS = 'EDIT_BLOGPOST_SUCCESS';
export const EDIT_BLOGPOST_ERROR = 'EDIT_BLOGPOST_ERROR';


export const DELETE_BLOGPOST_START = 'DELETE_BLOGPOST_START';
export const DELETE_BLOGPOST_SUCCESS = 'DELETE_BLOGPOST_SUCCESS';
export const DELETE_BLOGPOST_ERROR = 'DELETE_BLOGPOST_ERROR';

export const GET_BLOGPOSTS_BY_USER_START = 'GET_BLOGPOSTS_BY_USER_START';
export const GET_BLOGPOSTS_BY_USER_SUCCESS = 'GET_BLOGPOSTS_BY_USER_SUCCESS';
export const GET_BLOGPOSTS_BY_USER_ERROR = 'GET_BLOGPOST_BY_USER_ERROR';

export const GET_SINGLE_BLOGPOST_START = 'GET_SINGLE_BLOGPOST_START'
export const GET_SINGLE_BLOGPOST_SUCCESS = 'GET_SINGLE_BLOGPOST_SUCCESS'
export const GET_SINGLE_BLOGPOST_ERROR = 'GET_SINGLE_BLOGPOST_ERROR'

export const GET_ALL_BLOGPOSTS_START = 'GET_ALL_BLOGPOSTS_START'
export const GET_ALL_BLOGPOSTS_SUCCESS = 'GET_ALL_BLOGPOSTS_SUCCESS'
export const GET_ALL_BLOGPOSTS_ERROR = 'GET_ALL_BLOGPOSTS_ERROR'